name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # master
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # master
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec

  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # master
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Audit Ruby dependencies
        run: bundle exec bundle-audit check --update
